
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class BattlefieldDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement RootVisualElement => _rootVisualElement ??=
			uiDocument.rootVisualElement;

		private VisualElement _battlefield;
		private VisualElement _battlefieldPlayerStatHealthGauge;
		private VisualElement _battlefieldPlayerStatHealth;
		private VisualElement _battlefieldPlayerStatManaGauge;
		private VisualElement _battlefieldPlayerStatMana;
		private VisualElement _battlefieldMinimap;
		private Button _actionHelperMap;
		private Button _actionHelperPause;

		public VisualElement Battlefield => _battlefield ??=
			RootVisualElement.Q<VisualElement>("Battlefield");
		public VisualElement BattlefieldPlayerStatHealthGauge => _battlefieldPlayerStatHealthGauge ??=
			RootVisualElement.Q<VisualElement>("BattlefieldPlayerStatHealthGauge");
		public VisualElement BattlefieldPlayerStatHealth => _battlefieldPlayerStatHealth ??=
			RootVisualElement.Q<VisualElement>("BattlefieldPlayerStatHealth");
		public VisualElement BattlefieldPlayerStatManaGauge => _battlefieldPlayerStatManaGauge ??=
			RootVisualElement.Q<VisualElement>("BattlefieldPlayerStatManaGauge");
		public VisualElement BattlefieldPlayerStatMana => _battlefieldPlayerStatMana ??=
			RootVisualElement.Q<VisualElement>("BattlefieldPlayerStatMana");
		public VisualElement BattlefieldMinimap => _battlefieldMinimap ??=
			RootVisualElement.Q<VisualElement>("BattlefieldMinimap");
		public Button ActionHelperMap => _actionHelperMap ??=
			RootVisualElement.Q<Button>("ActionHelperMap");
		public Button ActionHelperPause => _actionHelperPause ??=
			RootVisualElement.Q<Button>("ActionHelperPause");

		private void Start()
		{
			if (uiDocument == null)
                Debug.LogError($"uiDocument field empty in {name} component", this);
		}
    }
}