
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class LevelSelectionDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement _levelSelection;

		public VisualElement LevelSelection => _levelSelection ??=
			_rootVisualElement.Q<VisualElement>("LevelSelection");

		private void Awake()
		{
			if (uiDocument == null)
            {
                Debug.LogError($"uiDocument field empty in {name} component", this);
				return;
			}

			_rootVisualElement = uiDocument.rootVisualElement;
		}
    }
}