
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class LevelSelectionDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement RootVisualElement => _rootVisualElement ??=
			uiDocument.rootVisualElement;

		private VisualElement _levelSelection;
		private VisualElement _levelSelectionTitle;
		private VisualElement _actionHelperSelect;
		private VisualElement _actionHelperBack;
		private VisualElement _levelSelectionInfo;
		private Label _levelSelectionInfoText;

		public VisualElement LevelSelection => _levelSelection ??=
			RootVisualElement.Q<VisualElement>("LevelSelection");
		public VisualElement LevelSelectionTitle => _levelSelectionTitle ??=
			RootVisualElement.Q<VisualElement>("LevelSelectionTitle");
		public VisualElement ActionHelperSelect => _actionHelperSelect ??=
			RootVisualElement.Q<VisualElement>("ActionHelperSelect");
		public VisualElement ActionHelperBack => _actionHelperBack ??=
			RootVisualElement.Q<VisualElement>("ActionHelperBack");
		public VisualElement LevelSelectionInfo => _levelSelectionInfo ??=
			RootVisualElement.Q<VisualElement>("LevelSelectionInfo");
		public Label LevelSelectionInfoText => _levelSelectionInfoText ??=
			RootVisualElement.Q<Label>("LevelSelectionInfoText");

		private void Start()
		{
			if (uiDocument == null)
                Debug.LogError($"uiDocument field empty in {name} component", this);
		}
    }
}