
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class MainMenuDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement RootVisualElement => _rootVisualElement ??=
			uiDocument.rootVisualElement;

		private VisualElement _mainMenu;
		private VisualElement _mainMenuLogo;
		private Button _mainMenuButtonNewGame;
		private Button _mainMenuButtonSettings;
		private Button _mainMenuButtonQuit;
		private VisualElement _actionHelperSelect;

		public VisualElement MainMenu => _mainMenu ??=
			RootVisualElement.Q<VisualElement>("MainMenu");
		public VisualElement MainMenuLogo => _mainMenuLogo ??=
			RootVisualElement.Q<VisualElement>("MainMenuLogo");
		public Button MainMenuButtonNewGame => _mainMenuButtonNewGame ??=
			RootVisualElement.Q<Button>("MainMenuButtonNewGame");
		public Button MainMenuButtonSettings => _mainMenuButtonSettings ??=
			RootVisualElement.Q<Button>("MainMenuButtonSettings");
		public Button MainMenuButtonQuit => _mainMenuButtonQuit ??=
			RootVisualElement.Q<Button>("MainMenuButtonQuit");
		public VisualElement ActionHelperSelect => _actionHelperSelect ??=
			RootVisualElement.Q<VisualElement>("ActionHelperSelect");

		private void Start()
		{
			if (uiDocument == null)
                Debug.LogError($"uiDocument field empty in {name} component", this);
		}
    }
}