
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class MapDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement _map;

		public VisualElement Map => _map ??=
			_rootVisualElement.Q<VisualElement>("Map");

		private void Start()
		{
			if (uiDocument == null)
            {
                Debug.LogError($"uiDocument field empty in {name} component", this);
				return;
			}

			_rootVisualElement = uiDocument.rootVisualElement;
		}
    }
}