
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class MapDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement RootVisualElement => _rootVisualElement ??=
			uiDocument.rootVisualElement;

		private VisualElement _map;
		private VisualElement _levelSelectionActionHelperSelect;
		private VisualElement _levelSelectionActionHelperBack;
		private VisualElement _mapTileInfo;

		public VisualElement Map => _map ??=
			RootVisualElement.Q<VisualElement>("Map");
		public VisualElement LevelSelectionActionHelperSelect => _levelSelectionActionHelperSelect ??=
			RootVisualElement.Q<VisualElement>("LevelSelectionActionHelperSelect");
		public VisualElement LevelSelectionActionHelperBack => _levelSelectionActionHelperBack ??=
			RootVisualElement.Q<VisualElement>("LevelSelectionActionHelperBack");
		public VisualElement MapTileInfo => _mapTileInfo ??=
			RootVisualElement.Q<VisualElement>("MapTileInfo");

		private void Start()
		{
			if (uiDocument == null)
                Debug.LogError($"uiDocument field empty in {name} component", this);
		}
    }
}