
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class PauseMenuDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement RootVisualElement => _rootVisualElement ??=
			uiDocument.rootVisualElement;

		private VisualElement _pauseMenu;
		private Button _pauseMenuButtonResume;
		private Button _pauseMenuButtonSettings;
		private Button _pauseMenuButtonMainMenu;
		private Button _pauseMenuButtonQuit;

		public VisualElement PauseMenu => _pauseMenu ??=
			RootVisualElement.Q<VisualElement>("PauseMenu");
		public Button PauseMenuButtonResume => _pauseMenuButtonResume ??=
			RootVisualElement.Q<Button>("PauseMenuButtonResume");
		public Button PauseMenuButtonSettings => _pauseMenuButtonSettings ??=
			RootVisualElement.Q<Button>("PauseMenuButtonSettings");
		public Button PauseMenuButtonMainMenu => _pauseMenuButtonMainMenu ??=
			RootVisualElement.Q<Button>("PauseMenuButtonMainMenu");
		public Button PauseMenuButtonQuit => _pauseMenuButtonQuit ??=
			RootVisualElement.Q<Button>("PauseMenuButtonQuit");

		private void Start()
		{
			if (uiDocument == null)
                Debug.LogError($"uiDocument field empty in {name} component", this);
		}
    }
}