
using UnityEngine;
using UnityEngine.UIElements;

/*
* This file was auto-generated by the UIToolkitAutoReferencesPostprocessor class
*/

namespace UIToolkitAutoReferences
{
    public class TutorialDocumentAutoReferences : MonoBehaviour
    {
        [SerializeField] private UIDocument uiDocument;
        
        private VisualElement _rootVisualElement;

		private VisualElement _tutorial;
		private Label _tutorialTitleLabel;
		private Label _tutorialInfoSubTitle;

		public VisualElement Tutorial => _tutorial ??=
			_rootVisualElement.Q<VisualElement>("Tutorial");
		public Label TutorialTitleLabel => _tutorialTitleLabel ??=
			_rootVisualElement.Q<Label>("TutorialTitleLabel");
		public Label TutorialInfoSubTitle => _tutorialInfoSubTitle ??=
			_rootVisualElement.Q<Label>("TutorialInfoSubTitle");

		private void Start()
		{
			if (uiDocument == null)
            {
                Debug.LogError($"uiDocument field empty in {name} component", this);
				return;
			}

			_rootVisualElement = uiDocument.rootVisualElement;
		}
    }
}